Add alibaba shared credential backends
apple/password-manager-resources pull request #147
Opened 2020-06-08 06:57 UTC by AshoneA

### Checklist
- [ ] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)
- [ ] The top-level JSON objects are sorted alphabetically 
- [ ] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update.

#### for websites-with-shared-credential-backends.json
- [ ] The new group serves login pages on each of the included domains, and those login page accept accounts from the others. (For example, we donât associate google.com.li to google.com, because google.com.li redirects to accounts.google.com for authentication.)

#### for change-password-URLs.json
- [ ] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)

2020-06-12 04:08 UTC, AshoneA commented
Because those websites all belong to Alibaba company, so I can login use the same account.

2020-07-13 17:30 UTC, rmondello commented
Would love to merge this @AshoneA! Can you fix up the merge conflict?

2020-07-16 09:06 UTC, AshoneA commented
@rmondello merged

2020-10-25 06:49 UTC, ame1234 approved these changes
Authoring name is arlyss engebretson

2020-10-25 22:55 UTC, rmondello commented
I asked people for some help with this one on Twitter, and it looks like it’s not the case that these domains are all sharing credentials. https://twitter.com/rmondello/status/1320489942884102146?s=21

2020-10-25 22:57 UTC, rmondello requested changes

2020-10-25 22:57 UTC, rmondello commented on quirks/websites-with-shared-credential-backends.json
> +        "tmall.com"
It’s not clear that this is right.

2020-12-24 19:06 UTC, closed without merging