Add Pinterest associated websites
apple/password-manager-resources pull request #398
Opened 2020-12-16 17:43 UTC by MartinDevi

### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for websites-with-shared-credential-backends.json
- [ ] There's evidence the domains are related (SSL certificates, DNS entries, valid links between sites, legal documents etc.)
- [x] The new group serves login pages on each of the included domains, and those login page accept accounts from the others. (For example, we don't associate `google.co.il` to `google.com`, because `google.co.il` redirects to `accounts.google.com` for authentication.)

2020-12-17 21:04 UTC, rmondello commented
These seem good, except pintrest.com, which is a redirect.

2020-12-17 21:04 UTC, rmondello requested changes
Should we remove pintrest.com?

2020-12-17 21:40 UTC, Cldfire commented
The `pintrest.com` entry would fit very well into the format defined in https://github.com/apple/password-manager-resources/issues/389 😄

2020-12-24 21:48 UTC, Cldfire commented
Thinking about this some more, it might not be worth adding `pintrest.com` to the format proposed in #389.

We can assume that `pintrest.com` was registered by Pinterest to prevent someone else from buying up the (very similar) domain and using it for phishing. There's no reason why a user of a password manager should encounter this redirect during normal web browsing. In fact, should the user end up with credentials associated with the `pintrest.com` domain, I would argue that that's an issue that should be corrected by the user; a password manager shouldn't attempt to transparently adjust for that.

With that in mind, I would agree with @rmondello; `pintrest.com` should be removed here.

2020-12-28 08:07 UTC, MartinDevi commented
Removed `pintrest.com`

2020-12-30 22:02 UTC, Cldfire commented on quirks/websites-with-shared-credential-backends.json
> +        "pin.it",
I'd say similar logic applies here; `pin.it` is a redirect and should be removed from this PR.

2020-12-30 22:03 UTC, Cldfire commented
Everything LGTM after removing `pin.it` :)

2020-12-30 22:07 UTC, Cldfire approved these changes

2021-01-05 21:31 UTC, rmondello approved these changes

2021-01-05 21:32 UTC, merged