Add bcassessment.ca - BC Assessment
apple/password-manager-resources pull request #482
Opened 2021-06-24 02:47 UTC by d19dotca

From the BC Assessment website when changing password: "Password must be at least 8-14 characters"

### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for password-rules.json
- [x] The given rule isn't particularly standard and obvious for password managers
- [x] Generated passwords have been tested from this rule using the [Password Rules Validation Tool](https://developer.apple.com/password-rules/)
- [x] Information has been included about the website's requirements (eg. screenshots, error messages, steps during experimentation, etc.)
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)

2021-06-24 19:21 UTC, rmondello requested changes

2021-06-24 19:21 UTC, rmondello commented on quirks/password-rules.json
> +    }
missing a trailing comma

2021-06-24 19:22 UTC, rmondello commented
Is there any more information you can derive from the website about requirements?

2021-06-24 20:05 UTC, d19dotca commented
> Is there any more information you can derive from the website about requirements?

The website only states the requirements listed earlier, unfortunately.

2021-07-03 15:44 UTC, d19dotca commented
Made the correction to the missing comma.

2021-07-07 15:40 UTC, rmondello approved these changes

2021-07-07 15:40 UTC, merged