Add and Update several password change urls
apple/password-manager-resources pull request #665
Opened 2023-01-26 21:47 UTC by joshka

### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for change-password-URLs.json
- [x] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)
- [x] The URL either makes the experience better or no worse than being directed to just the domain in a non-logged-in state

2023-01-27 02:21 UTC, simap-ag commented
Can you remove  commit [03e1675](https://github.com/apple/password-manager-resources/pull/665/commits/03e167596d9e0a1984cab37e9cfab27fd64cc747), as I have it in another pull request already.

2023-01-28 08:17 UTC, joshka commented
> Can you remove commit [03e1675](https://github.com/apple/password-manager-resources/pull/665/commits/03e167596d9e0a1984cab37e9cfab27fd64cc747), as I have it in another pull request already.

Done.

2023-01-30 13:28 UTC, rmondello requested changes
Looks great to me. Awesome contribution! I left a few comments about `www.`. After addressing some of those, I’d be thrilled to merge this.

2023-01-30 13:28 UTC, rmondello commented on quirks/change-password-URLs.json
> +    "crackle.com": "https://www.crackle.com/profile",
Can we remove `www.`?

2023-01-30 13:28 UTC, rmondello commented on quirks/change-password-URLs.json
> +    "columbia.com": "https://www.columbia.com/profile",
Can we remove `www.`?

2023-01-30 13:28 UTC, rmondello commented on quirks/change-password-URLs.json
> +    "cakeresume.com": "https://www.cakeresume.com/settings/account?ref=navs_settings",
Can we remove `www.`?

2023-01-30 13:28 UTC, rmondello commented on quirks/change-password-URLs.json
> +    "alaskaair.com": "https://www.alaskaair.com/www2/ssl/myalaskaair/myalaskaair.aspx?view=myinformation&tab=email",
Can we remove `www.`?

2023-01-30 13:28 UTC, rmondello commented on quirks/change-password-URLs.json
> +    "airnewzealand.com": "https://www.airnewzealand.com/membership/profile/security/password",
Can we remove `www.`?

2023-01-30 14:17 UTC, joshka commented
Removing www seems generally wrong to me on these. The sites in question have chosen to use the prefix as their canonical url (all urls are copied from a live session using the site). The non-www version might work in some cases, but is not the url that the sites advertise themselves. I get the arguments both ways on no-www and yes-www sides of the issue (I lean no-www, but not enough to try to argue for it), but the decision is the target website owner’s not the browser / tool maker’s.

This said - it’s entirely possible there’s something technical I’m missing that’s not stated in why you want the www dropped - help me understand if I have?

2023-01-30 14:22 UTC, rmondello commented
@joshka If these are, in fact, the canonical URLs, then this is great!

2023-01-30 14:23 UTC, rmondello approved these changes

2023-01-30 14:23 UTC, merged

2023-01-30 14:23 UTC, rmondello commented
Thanks for the contribution, @joshka!